const taskModel = [
  {
    id: 1,
    title: "Set up environment",
    description: "Install Node.js, npm, and git",
    completed: true,
    priority: "medium",
    createdAt: Date.now(),
  },
  {
    id: 2,
    title: "Create a new project",
    description: "Create a new project using the Express application generator",
    completed: true,
    priority: "low",
    createdAt: Date.now(),
  },
  {
    id: 3,
    title: "Install nodemon",
    description: "Install nodemon as a development dependency",
    completed: true,
    priority: "medium",
    createdAt: Date.now(),
  },
  {
    id: 4,
    title: "Install Express",
    description: "Install Express",
    completed: false,
    priority: "low",
    createdAt: Date.now(),
  },
  {
    id: 5,
    title: "Install Mongoose",
    description: "Install Mongoose",
    completed: false,
    priority: "high",
    createdAt: Date.now(),
  },
  {
    id: 6,
    title: "Install Morgan",
    description: "Install Morgan",
    completed: false,
    priority: "high",
    createdAt: Date.now(),
  },
  {
    id: 7,
    title: "Install body-parser",
    description: "Install body-parser",
    completed: false,
    priority: "low",
    createdAt: Date.now(),
  },
  {
    id: 8,
    title: "Install cors",
    description: "Install cors",
    completed: false,
    priority: "medium",
    createdAt: Date.now(),
  },
  {
    id: 9,
    title: "Install passport",
    description: "Install passport",
    completed: false,
    priority: "medium",
    createdAt: Date.now(),
  },
  {
    id: 10,
    title: "Install passport-local",
    description: "Install passport-local",
    completed: false,
    priority: "medium",
    createdAt: Date.now(),
  },
  {
    id: 11,
    title: "Install passport-local-mongoose",
    description: "Install passport-local-mongoose",
    completed: false,
    priority: "high",
    createdAt: Date.now(),
  },
  {
    id: 12,
    title: "Install express-session",
    description: "Install express-session",
    completed: false,
    priority: "low",
    createdAt: Date.now(),
  },
  {
    id: 13,
    title: "Install connect-mongo",
    description: "Install connect-mongo",
    completed: false,
    priority: "low",
    createdAt: Date.now(),
  },
  {
    id: 14,
    title: "Install dotenv",
    description: "Install dotenv",
    completed: false,
    priority: "medium",
    createdAt: Date.now(),
  },
  {
    id: 15,
    title: "Install jsonwebtoken",
    description: "Install jsonwebtoken",
    completed: false,
    priority: "high",
    createdAt: Date.now(),
  },
];

module.exports = taskModel;
